### ISSUE TITLE
Saving HTML when updating html.md to embed_local_images: true doesn't embed images in output .html

### ISSUE THREAD

**Issue by MarkDVerhagen** [shd101wyy/vscode-markdown-preview-enhanced#1269]
**Using** 
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

Updated the relevant part of my *html.md* file in the markdown-preview-enhanced package to the following:

```
## Configuration
Default values:
yaml
---
html:
  embed_local_images: true
  embed_svg: true
  offline: false
  toc: undefined

print_background: false
---
```

Although right-clicking the preview tab and saving as html (either offline or cdn-hosted) doesn't yield a .html file with embedded images. Do I not understand embedded images to mean that the .html contains the image files, i.e. there is no need to attach the raw images when sending the .html, or is something else going wrong?

I've restarted atom after updating the configurations
