### ISSUE TITLE
请问如何修改粗体文字的 css 样式?

### ISSUE THREAD

**Issue by ShaunWuu** [shd101wyy/vscode-markdown-preview-enhanced#1340]
如题, 谢谢!

使用如下 css 貌似无效?
```css
  bold {
    color: #d8dee9;
  }
```
