### ISSUE TITLE
Mermaid .png not saving to imageFolderPath

### ISSUE THREAD

**Issue by SeaDude** [shd101wyy/vscode-markdown-preview-enhanced#1526]
Hello, 

Great tool! Its taken my documentation skills waaaay up a notch. 

**Issue:** Mermaid .png is NOT writing to `/assets`. 

**Setup:**
- Workspace: 
```
/git/myDir/assets
```
- User Settings: 
```
"markdown-preview-enhanced.imageFolderPath": "/assets"
```
- Front matter in `/myDir/test.md` file:
```
markdown: 
    image_dir: /assets
    path: test1.md
    ignore_from_front_matter: true
    absolute_image_path: false
    export_on_save:
    markdown: true
```
- Mermaid in `/myDir/test.md` file: 
```
mermaid {filename="test.png"}
        graph LR
            test --> test1;
```
- Right click in preview, `Save as Markdown`
- Success message, `/myDir/test1.md` shows up just fine
- NO `test.png` in `/myDir/assets`

What am I missing?
