### ISSUE TITLE
引用的css和在style.less中定义的css似乎都不生效

### ISSUE THREAD

**Issue by TTTPOB** [shd101wyy/vscode-markdown-preview-enhanced#153]
默认的中文字体是宋体，我想更改字体。
但是这两种方式似乎都没有效果，不知道我需要提供什么信息来帮助您定位问题？

**Comment by shd101wyy** [comment]
你是怎么修改的 style.less 呢？把你的发给我看看？来张截图？

**Comment by TTTPOB** [comment]
![image](https://user-images.githubusercontent.com/19909103/47223185-2d903180-d3eb-11e8-8cc3-e7864334c531.png)
这样的。
字体我找不到在线的这个字体所以。。。但是我也试了思源黑体，用的google fonts, 我这里能够访问google fonts api，但是依然不起效果。

**Comment by shd101wyy** [comment]
@TTTPOB 可以这么写 `style.less`:

```less
@font-face {
  font-family: "Sarasa";
  src: url('C:/Windows/Fonts/sarasa-term-sc-regular.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

.markdown-preview.markdown-preview {
  font-family: "Sarasa", sans-serif;

  h1, h2, h3, h4, h5, h6, pre, code {
    font-family: "Sarasa", sans-serif;
  }
}
```
