### ISSUE TITLE
Customizing tab spaces count in code blocks

### ISSUE THREAD

**Issue by dylankb** [shd101wyy/vscode-markdown-preview-enhanced#1549]
In case this is helpful to anyone else, you can customize the default number of spaces (currently 4) that represent a tab in your code blocks by doing the following

- Go to `Cmd+Shift+p` and enter Mardown Preview Enhanced: Customize Css
- Edit your default file so it looks like the one below (if you want to change the default to 2 spaces / tab)

```css
.markdown-preview.markdown-preview {
  pre[data-role="codeBlock"] {
    tab-size: 2;
  }
}
```
