### ISSUE TITLE
Specifying the HTML output path

### ISSUE THREAD

**Issue by rcmalli** [shd101wyy/vscode-markdown-preview-enhanced#1699]
Is there a way to define output path for the file when we are exporting as HTML document (CDN or Offline)? None of the settings below works.

```yaml
path: test.html
html:
    embed_local_images: true
    embed_svg: true
    path: test.html
output:
    html:
        path: test.html
export_on_save:
    html: true
```
