### ISSUE TITLE
export_on_save no longer works in v 0.7.2

### ISSUE THREAD

**Issue by juanjobalmis** [shd101wyy/vscode-markdown-preview-enhanced#1742]
Configuration in frontmatter...

``` yaml
export_on_save:
    puppeteer: true
    html: true
```

It does not work, but yes whether I export it manually.

Regards,
