### ISSUE TITLE
[BUG] list element hierarchy error in v0.8.0

### ISSUE THREAD

**Issue by byte-clown** [shd101wyy/vscode-markdown-preview-enhanced#1797]
**Describe the bug**
Incorrect hierarchy structure of elements after list element

**Environment**
- OS: Windows 10
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**
colors.less:

```less
// out: false

@blue-100: #cfe2ff;
@blue-200: #9ec5fe;
@blue-300: #6ea8fe;
@blue-400: #3d8bfd;
@blue-500: #0d6efd;
@blue-600: #0a58ca;
@blue-700: #084298;
@blue-800: #052c65;
@blue-900: #031633;
@indigo-100: #e0cffc;
@indigo-200: #c29ffa;
@indigo-300: #a370f7;
@indigo-400: #8540f5;
@indigo-500: #6610f2;
@indigo-600: #520dc2;
@indigo-700: #3d0a91;
@indigo-800: #290661;
@indigo-900: #140330;
@purple-100: #e2d9f3;
@purple-200: #c5b3e6;
@purple-300: #a98eda;
@purple-400: #8c68cd;
@purple-500: #6f42c1;
@purple-600: #59359a;
@purple-700: #432874;
@purple-800: #2c1a4d;
@purple-900: #160d27;
@pink-100: #f7d6e6;
@pink-200: #efadce;
@pink-300: #e685b5;
@pink-400: #de5c9d;
@pink-500: #d63384;
@pink-600: #ab296a;
@pink-700: #801f4f;
@pink-800: #561435;
@pink-900: #2b0a1a;
@red-100: #f8d7da;
@red-200: #f1aeb5;
@red-300: #ea868f;
@red-400: #e35d6a;
@red-500: #dc3545;
@red-600: #b02a37;
@red-700: #842029;
@red-800: #58151c;
@red-900: #2c0b0e;
@orange-100: #ffe5d0;
@orange-200: #fecba1;
@orange-300: #feb272;
@orange-400: #fd9843;
@orange-500: #fd7e14;
@orange-600: #ca6510;
@orange-700: #984c0c;
@orange-800: #653208;
@orange-900: #331904;
@yellow-100: #fff3cd;
@yellow-200: #ffe69c;
@yellow-300: #ffda6a;
@yellow-400: #ffcd39;
@yellow-500: #ffc107;
@yellow-600: #cc9a06;
@yellow-700: #997404;
@yellow-800: #664d03;
@yellow-900: #332701;
@green-100: #d1e7dd;
@green-200: #a3cfbb;
@green-300: #75b798;
@green-400: #479f76;
@green-500: #198754;
@green-600: #146c43;
@green-700: #0f5132;
@green-800: #0a3622;
@green-900: #051b11;
@teal-100: #d2f4ea;
@teal-200: #a6e9d5;
@teal-300: #79dfc1;
@teal-400: #4dd4ac;
@teal-500: #20c997;
@teal-600: #1aa179;
@teal-700: #13795b;
@teal-800: #0d503c;
@teal-900: #06281e;
@cyan-100: #cff4fc;
@cyan-200: #9eeaf9;
@cyan-300: #6edff6;
@cyan-400: #3dd5f3;
@cyan-500: #0dcaf0;
@cyan-600: #0aa2c0;
@cyan-700: #087990;
@cyan-800: #055160;
@cyan-900: #032830;
@gray-100: #f8f9fa;
@gray-200: #e9ecef;
@gray-300: #dee2e6;
@gray-400: #ced4da;
@gray-500: #adb5bd;
@gray-600: #6c757d;
@gray-700: #495057;
@gray-800: #343a40;
@gray-900: #212529;
```

style.less:

```less
/* Please visit the URL below for more information: */
/*   https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css */

@import "colors.less";

@margin: 16px;

.markdown-preview {
    // images

    img {
        cursor: zoom-in;

        &.error {
            width: 48px;
            height: 48px;
            border: none;
            box-shadow: none;
            background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACXBIWXMAAAsTAAALEwEAmpwYAAADMklEQVR4nO2Y70sUQRjHvyVFJRmK0t3sWRBoalCQhPmytBTqjf9B+bpXiXdz9OMsCPoX1NnT6p1/QZC3CpKvLHJ3tRDk3NFT0tuQflj4ZmMscW/d7s7y9g7aDzxvZmeG73d259l5BvDx8fHx8fH5zwj2p04RttQqyYsXmkb0wygVzAQepcfQ7vasuX/qUHCQ3yHMmJNkbm0HYcaGxIx4aJhLKDamgpSZQJ+zPdifqpYYn7AL3xXMSEvyYosnQj+N4aapoMfFwFJawUN7W0BeriHMULOKl3dM1DKDFNyAEG8qsNIJPLC3r75C/foEKrOLN74QxmOhOO8gzLhFZENzGBmCFwjxwoQ5hk63527iicxTwaFkg71faIQflRh/YzP47eTzlXJPTJgKOqwRlDnbz/TPn3ATL8UX69zmIYx32/uG4vwSiklAXmgiMt/MR7yAsIW2TLOGaybzlJDMu4SJXOIFhPH7dgO1A8Y5FAKRYdIK5kWsjiOrKEEwvnAxV34PDiUbxMa2va1lWNYBFIL0KK6lE3hqJvDEnm3+FsKWzm69IdvqB2UehqfE5ioQ1Zv2Okx8VsQhXpKNSW+PFtG3NaC6CqpvIqJ25TuMDCzVO8UTZqgi9aII4q3fsQmqNucaJg0shkpRvAWqpRCeDuUaGhw0mjNSLCsV8b0zObPSNhJbuEFk/kOS+ezpoWQAnhFLHkFEn3SIX0FYa9zrVIHBZGPVi7kKeArV7u2HeCfrE6g0FURErI3iCgpCzDoIqn+0if8MOlufdYzYE3ls7NVx1G3/IJ3H8f0jqp7PXH09mrW/MCf2xh5TbOGg2vUMAxH9ah7id1LsPnxq/0Z49nKmAbU7T/Ei1K0/tgNrBGXiSA5P6HlXjoj23SZqFr3vj2f0EavsJl6kXhfMMXS6VXaFg+rPHFlIB9Vvg+qdiGiPQfWv2cSvv0SVKDtdKztld429/9zTakG1NYfIP8WulRcZRhT+zmlNBT3iogCeQNXWPEy8xt0P1buEJtAnrl5QdMLTIUS0YVB9I3Nja8uIamHE3I/Eawra3O6Nikds6hjoTAvoTPuvmqBAlZSPj4+Pj48PSpOfMc7Sdo2GhWEAAAAASUVORK5CYII=');
            background-position: center;
            background-repeat: no-repeat;
            cursor: pointer;
        }
    }

    figure {
        max-width: 100%;
        margin-block-start: 0;
        margin-block-end: @margin;
        margin-inline-start: 0;
        margin-inline-end: 0;

        img {
            box-shadow: rgba(0, 0, 0, 0.15) 0px 1px 4px;
            max-width: ~"min(100%, 850px)";
        }

        figcaption {
            font-size: 0.8em;
        }
    }

    // list

    li>p:first-child,
    li>p:first-child~p,
    li>p:first-child~ul,
    li>p:first-child~ol {
        margin-bottom: @margin;
    }

    // table

    table {
        td>:last-child {
            margin-bottom: 0;
        }
    }

    // emphasis

    strong,
    del {
        color: inherit;
    }

    // code

    code {
        background-color: initial;
        font-size: 0.85em !important;
        vertical-align: 0.075em;
        border: none;
        padding: 0;

        &::before,
        &::after {
            content: none;
        }
    }

    pre {
        tab-size: 4;

        &.wrap,
        &.wrap>code {
            white-space: pre-wrap;
            word-break: break-word;
        }

        &[data-line] {
            .line-highlight-wrapper {
                pointer-events: none;

                .line-highlight {
                    background: hsla(24, 20%, 50%, .08);
                }

                .line-highlight:before,
                .line-highlight[data-end]:after {
                    content: none;
                }
            }
        }
    }

    // blockquotes

    blockquote {
        overflow: auto;
    }

    // color theme

    &.editor-light,
    body[for="html-export"]>& {
        .color-theme(true);
    }

    &.editor-dark {
        .color-theme(false);
    }
}

// copied tip

.copied-tip {
    z-index: 999;
    pointer-events: none;
    font-size: 0.8em;
}

.color-theme(@is-light) {
    @fg: if(@is-light, @gray-900, @gray-300);
    @bg: if(@is-light, #fff, #1f1f1f);
    @strong-fg: if(@is-light, #000, #fff);
    @subtle-fg: if(@is-light, @gray-700, @gray-500);
    @default-fg: if(@is-light, @gray-800, @gray-300);
    @default-bg: if(@is-light, @gray-100, @gray-900);
    @default-nest-bg: if(@is-light, @gray-200, @gray-800);
    @default-bdr: if(@is-light, @gray-200, @gray-700);
    @info-fg: if(@is-light, @blue-800, @blue-300);
    @info-bg: if(@is-light, @blue-100, @blue-900);
    @info-nest-bg: if(@is-light, @blue-200, @blue-800);
    @info-bdr: if(@is-light, @blue-200, @blue-700);
    @warn-fg: if(@is-light, @yellow-800, @yellow-300);
    @warn-bg: if(@is-light, @yellow-100, @yellow-900);
    @warn-nest-bg: if(@is-light, @yellow-200, @yellow-800);
    @warn-bdr: if(@is-light, @yellow-200, @yellow-700);
    @danger-fg: if(@is-light, @red-800, @red-300);
    @danger-bg: if(@is-light, @red-100, @red-900);
    @danger-nest-bg: if(@is-light, @red-200, @red-800);
    @danger-bdr: if(@is-light, @red-200, @red-700);
    @link-fg: if(@is-light, @blue-500, @blue-300);
    @link-hover-fg: if(@is-light, @blue-600, @blue-200);
    @code-fg: if(@is-light, @pink-500, @pink-300);

    color: @fg;
    background-color: @bg;

    // headings

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        color: @strong-fg;
    }

    h6 {
        color: @subtle-fg;
    }

    // link

    a {
        color: @link-fg;

        &:hover {
            color: @link-hover-fg;
        }

        img {
            cursor: pointer;
        }

        @escaped-link-fg: escape("@{link-fg}");
        @escaped-link-hover-fg: escape("@{link-hover-fg}");
        @vsc-res: "https://file+.vscode-resource.vscode-cdn.net/";

        &[href^="@{vsc-res}"][href$=".md"]:not(.noicon)::before,
        &[href^="@{vsc-res}"][href*=".md#"]:not(.noicon)::before {
            content: url('data:image/svg+xml,<svg fill="none" stroke="@{escaped-link-fg}" stroke-width="1.85" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"></path></svg>');
            line-height: 1em;
            margin-right: 0.2em;
            vertical-align: text-bottom;
        }

        &[href^="@{vsc-res}"]:not(.noicon):not([href$=".md"]):not([href*=".md#"]):before {
            content: url('data:image/svg+xml,<svg fill="none" stroke="@{escaped-link-fg}" stroke-width="1.85" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"></path></svg>');
            line-height: 1em;
            margin-right: 0.2em;
            vertical-align: text-bottom;
        }

        &[href^="http"]:not([href^="@{vsc-res}"]):not(.noicon)::after {
            content: url('data:image/svg+xml,<svg fill="none" stroke="@{escaped-link-fg}" stroke-width="1.85" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"></path></svg>');
            line-height: 1em;
            margin-left: 0.2em;
            vertical-align: text-bottom;
        }

        &[href^="@{vsc-res}"][href$=".md"]:not(.noicon):hover::before,
        &[href^="@{vsc-res}"][href*=".md#"]:not(.noicon):hover::before {
            content: url('data:image/svg+xml,<svg fill="none" stroke="@{escaped-link-hover-fg}" stroke-width="1.85" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"></path></svg>');
        }

        &[href^="@{vsc-res}"]:not(.noicon):not([href$=".md"]):not([href*=".md#"]):hover::before {
            content: url('data:image/svg+xml,<svg fill="none" stroke="@{escaped-link-hover-fg}" stroke-width="1.85" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"></path></svg>');
        }

        &[href^="http"]:not([href^="@{vsc-res}"]):not(.noicon):hover::after {
            content: url('data:image/svg+xml,<svg fill="none" stroke="@{escaped-link-hover-fg}" stroke-width="1.85" width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"></path></svg>');
        }
    }

    // hr

    hr {
        background-color: @default-bdr;
    }

    // table

    table {
        th {
            color: @strong-fg;
        }

        td,
        th {
            border-color: @default-bdr;
        }
    }

    // emphasis

    mark {
        color: @warn-fg;
        background-color: @warn-bg;

        &.info {
            color: @info-fg;
            background-color: @info-bg;
        }

        &.danger {
            color: @danger-fg;
            background-color: @danger-bg;
        }
    }

    // code

    :not(pre)>code {
        color: @code-fg;
    }

    pre {
        color: @default-fg;
        background-color: @default-bg !important;
    }

    // blockquotes

    blockquote {
        color: @default-fg;
        background-color: @default-bg;
        border-color: @default-bdr;

        &:not(.info):not(.warn):not(.danger) pre {
            background-color: @default-nest-bg !important;
        }

        &.info {
            color: @info-fg;
            background-color: @info-bg;
            border-left-color: @info-bdr;

            mark.info {
                background-color: @info-nest-bg;
            }
        }

        &.warn {
            color: @warn-fg;
            background-color: @warn-bg;
            border-left-color: @warn-bdr;

            mark:not(.info):not(.danger) {
                background-color: @warn-nest-bg;
            }
        }

        &.danger {
            color: @danger-fg;
            background-color: @danger-bg;
            border-left-color: @danger-bdr;

            mark.danger {
                background-color: @danger-nest-bg;
            }
        }
    }

    // kbd

    kbd {
        color: @strong-fg;
        background-color: @default-bg;
        border-color: @default-bdr;
    }
}
```

markdown file:

```markdown
1. Lorem ipsum dolor sit amet consectetur adipisicing elit.

   - Lorem ipsum dolor sit amet consectetur adipisicing elit.
   - Lorem ipsum dolor sit amet consectetur adipisicing elit.
   - Lorem ipsum dolor sit amet consectetur adipisicing elit.

   > **Tip 1**
   >
   > Lorem ipsum dolor sit amet consectetur adipisicing elit.
   >
   > ```Text {.wrap}
   > Lorem ipsum dolor sit amet consectetur adipisicing elit.
   > ```

   > **Tip 2**
   >
   > Lorem ipsum dolor sit amet consectetur adipisicing elit.
   >
   > ```Text {.wrap}
   > Lorem ipsum dolor sit amet consectetur adipisicing elit.
   > ```

2. Lorem ipsum dolor sit amet consectetur adipisicing elit.

   Lorem ipsum dolor sit amet consectetur adipisicing elit.
```

**Expected behavior**

html in preview (expected, v0.7.10):

```html
<ol>
  <li>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    <ul>
      <li>Lorem ipsum dolor sit amet consectetur adipisicing elit.</li>
      <li>Lorem ipsum dolor sit amet consectetur adipisicing elit.</li>
      <li>Lorem ipsum dolor sit amet consectetur adipisicing elit.</li>
    </ul>
    <blockquote>
      <p><strong>Tip 1</strong></p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
      <pre><code>Lorem ipsum dolor sit amet consectetur adipisicing elit.</code></pre>
    </blockquote>
    <blockquote>
      <p><strong>Tip 2</strong></p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
      <pre><code>Lorem ipsum dolor sit amet consectetur adipisicing elit.</code></pre>
    </blockquote>
  </li>
  <li>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
  </li>
</ol>
```

html in preview (actually, v0.8.0):

```html
<ol>
  <li>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    <ul>
      <li><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p></li>
      <li><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p></li>
      <li><p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p></li>
    </ul>
    <blockquote>
      <p><strong>Tip 1</strong></p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
      <pre><code>Lorem ipsum dolor sit amet consectetur adipisicing elit.</code></pre>
    </blockquote>
  </li>
</ol>
<blockquote>
  <p><strong>Tip 2</strong></p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
  <pre><code>Lorem ipsum dolor sit amet consectetur adipisicing elit.</code></pre>
</blockquote>
<ol>
  <li>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
  </li>
</ol>
```

> tip: all `data-source-line` tags in the preview have been removed.

**Screenshots**

html diff:

![diff](https://raw.githubusercontent.com/byte-clown/picbed/main/markdown/2023-10-06-15-12-52.png)

preview in v0.7.10:

![before](https://raw.githubusercontent.com/byte-clown/picbed/main/markdown/2023-10-06-15-21-50.png)

preview in v0.8.0:

![after](https://raw.githubusercontent.com/byte-clown/picbed/main/markdown/2023-10-06-15-19-16.png)
