### ISSUE TITLE
[BUG] 文字中含有中文冒号：时，加粗显示异常

### ISSUE THREAD

**Issue by SolemnJudgment** [shd101wyy/vscode-markdown-preview-enhanced#1811]
# **Describe the bug**
文字中含有中文冒号：时，加粗显示异常

# **Environment**
- OS: Windows 11
- VSCode: 1.81.0
- Markdown Preview Enhanced: 0.8.1

# **Expected behavior**
文字中含有中文冒号：时，加粗显示异常

# **Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/85673749/f87e5ae6-3e43-4289-9b8f-8cf7345f0bbe)

**Comment by Saraswatica** [comment]
请教一个问题，最近更新的版本，preview的末尾都有个End of document，怎么去掉这个东西
<img width="114" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/147289830/44b07f97-e4bd-40c1-896b-1c8d4447954e">

**Comment by shd101wyy** [comment]
@Saraswatica `Markdown Preview Enhanced: Customize Css` 然后编辑 `style.less`:

```less
.markdown-preview.markdown-preview {
  .end-of-document::before {
    content: "" !important;
  }
}
```

@SolemnJudgment 我测试了冒号没有问题，你是不是有多余的空格？

**步骤同上：**

```
**步骤同上：**
```
