### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by zerzerzerz** [shd101wyy/vscode-markdown-preview-enhanced#1819]
**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'content')

**Environment**
- OS: Windows 10
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.2

**To Reproduce**
1. click the "open the preview on the side" button

**Expected behavior**
render the preview

**Markdown file**
any markdown file will lead to this error

**Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/69133585/172ee05d-99b3-431a-843e-37c4cbb695cd)

**Additional context**

**Comment by zerzerzerz** [comment]
It works well with version 0.8.1. But when I update it to version 0.8.2, it will lead to this error.

**Comment by LangLangBart** [comment]
- the issue seems to have come from upgrading the `crossnote` package in
  a060d5219d3776b7b8503da172f62a8821d50c21 to `"crossnote": "^0.8.20"`
	- upgrading the package to `0.8.21` in a commit after the release of `v0.8.2` seems to not
	have fixed the issue yet

---

- the problem can be reproduced by using the following Markdown file and opening the preview

```md
- an image link
- ![](/assets/images/2023-10-02-09-29-36.png)
```

---

> [!NOTE]
> using the `img` tag does work correctly

```md
<img src="" width="300">
```

**Comment by LangLangBart** [comment]
- the `"crossnote": "^0.8.22"` version seems to have fixed the issue (at least for me)

**Comment by shd101wyy** [comment]
Yes I also published a new release of the extension. So it should be working now. Sorry for the trouble.

**Comment by Paradox98** [comment]
I'm having a similar but not the same problem.
> TypeError: Cannot read properties of undefined (reading '**level**') 


When I type
```
---
html:
  embed_local_images: true
  embed_svg: true
  offline: true
  toc: true
print_background: true
export_on_save:
  html: true
toc:
  depth_from: 2
  depth_to: 6
  ordered: false
date: 2023-11-17
updated: 2023-11-17
author: xxx
---
[txt2](https:/tsadqiwb.com)
```
