### ISSUE TITLE
Export to PDF (prince) not coloring full page 

### ISSUE THREAD

**Issue by DolphinDream** [shd101wyy/vscode-markdown-preview-enhanced#1907]
**Describe the bug**
When using prince css settings to color the entire page a given color the export to PDF from this extension generates a PDF that has white background. Entering the same css (and html) on the prince’s site directly it generates a correct PDF. See the attachments.

**Environment**
- VSCode: 1.85.1
- Markdown Preview Enhanced: 0.8.11

**How to reproduce**
Use a simple markdown (See “Some Document.md” attachment) (multiple paragraphs with title and headings).. and the css settings to color the entire page a given color (for prince pdf export)

```css
body {
  background-color: plum;
  padding: 50px;
}

@page {
  background-color: plum;
  padding: 100px;
  margin: 50px;
}
```

with proper integration in the extension’s style.less file:

```css
/* Please visit the URL below for more information: */
/*   https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css */

.markdown-preview.markdown-preview {
  &.prince {
    body {
      background-color: plum;
      padding: 50px;
    }

    @page {
      background-color: plum;
      padding: 100px;
      margin: 50px;
    }
  }
}
```

The same markdown (as html) / css entered on **prince’s** site (https://www.princexml.com/try/) generates this PDF (entire page is plum).

<img width="1395" alt="Screen Shot 2023-12-20 at 5 57 40 PM" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/2083719/9c2b07be-9c22-4f5b-ab6b-4e1add116ebd">

[Some Document - prince.pdf](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/13733298/Some.Document.-.prince.pdf)

While the Markdown Preview Enhanced extension generates this PDF (edges of the page are plum with the center white)

<img width="1439" alt="Screen Shot 2023-12-20 at 5 57 54 PM" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/2083719/bf248b80-4a0b-4927-ba4a-954b02e51a31">

[Some Document.pdf](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/13733335/Some.Document.pdf)

The original markdown:

[Some Document.md](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/13733340/Some.Document.md)

And the html entered on prince’s site (same content as the markdown):

[Some Document.html.zip](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/13733369/Some.Document.html.zip)
