### ISSUE TITLE
[Feature Request] support callout 

### ISSUE THREAD

**Issue by zhuzhzh** [shd101wyy/vscode-markdown-preview-enhanced#1911]
callout is one concept from Obsidian. See https://help.obsidian.md/Editing+and+formatting/Callouts

github already supports it. see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

It looks mkdocs can support it with the plugin. See https://pypi.org/project/mkdocs-callouts/

> ![Note] This is one Note
> try it

Please help check if MPE can support callout. Thanks!

**Comment by bjesuiter** [comment]
I support this request, would be very nice to have!

**Comment by marcorossiIT** [comment]
related to #636

**Comment by brandonpeebles** [comment]
Any update on this? Would love this feature!

**Comment by sun-cube** [comment]
Would love to have this.

**Comment by ajkdrag** [comment]
I need this, so that docs can be compatible with Github and Obsidian and Foam.

**Comment by EmmetZ** [comment]
Since MPE can extend its markdown parser, I ask google gemini to write a parser for me to convert callout to [Admonition](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=admonition) which is supported by MPE. And it works quite good! 😀

You can replace the global markdown parser function `onWillParseMarkdown` with the following code in the `parser.js` file. (click <kbd>ctrl+shift+p</kbd> in vscode and search `Markdown Preview Enhanced: Extend Parser (Global)`)

```js
onWillParseMarkdown: async function (markdown) {
  return new Promise((resolve, reject) => {
    const calloutRegex = /^> ?\[!(?<type>\w+)\](?<title>.*)?\r?\n(?<content>(?:>.*\r?\n?)*)/gm;
    const newMarkdown = markdown.replace(
      calloutRegex,
      (match, type, title, content) => {
        const admonitionType = type.toLowerCase();
        const admonitionTitle = title && title.trim() ? `${title.trim()}` : "";

        const admonitionContent = content
          .replace(/^> ?/gm, "")
          .split(/\r?\n/)
          .map((line) => `    ${line}`)
          .join("\n");
        return `!!! ${admonitionType} ${admonitionTitle}\n${admonitionContent}\n\n`;
      }
    );
    return resolve(newMarkdown);
  });
}
```

preview:

<img width="1624" height="636" alt="Image" src="https://github.com/user-attachments/assets/4fe7b23d-34a4-440d-943e-e47f3e7738fc" />

**Comment by zhuzhzh** [comment]
> Since MPE can extend its markdown parser, I ask google gemini to write a parser for me to convert callout to [Admonition](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=admonition) which is supported by MPE. And it works quite good! 😀
> 
> You can replace the global markdown parser function `onWillParseMarkdown` with the following code in the `parser.js` file. (click ctrl+shift+p in vscode and search `Markdown Preview Enhanced: Extend Parser (Global)`)
> 
> onWillParseMarkdown: async function (markdown) {
>   return new Promise((resolve, reject) => {
>     const calloutRegex = /^> ?\[!(?<type>\w+)\](?<title>.*)?\r?\n(?<content>(?:>.*\r?\n?)*)/gm;
>     const newMarkdown = markdown.replace(
>       calloutRegex,
>       (match, type, title, content) => {
>         const admonitionType = type.toLowerCase();
>         const admonitionTitle = title && title.trim() ? `${title.trim()}` : "";
> 
>         const admonitionContent = content
>           .replace(/^> ?/gm, "")
>           .split(/\r?\n/)
>           .map((line) => `    ${line}`)
>           .join("\n");
>         return `!!! ${admonitionType} ${admonitionTitle}\n${admonitionContent}\n\n`;
>       }
>     );
>     return resolve(newMarkdown);
>   });
> }
> 
> preview:
> <img alt="Image" width="1624" height="636" src="https://private-user-images.githubusercontent.com/139854496/462731029-4fe7b23d-34a4-440d-943e-e47f3e7738fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI3MzMzNzksIm5iZiI6MTc1MjczMzA3OSwicGF0aCI6Ii8xMzk4NTQ0OTYvNDYyNzMxMDI5LTRmZTdiMjNkLTM0YTQtNDQwZC05NDNlLWU0N2YzZTc3MzhmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxN1QwNjE3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2E4YmRkOWVlMTFlODA0MmRkY2YyZjAwNThjNGY5Y2NlYzRmMTVhOTQ0MGM4OTU1ZTlmNWE4Yzc0OTUyNWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Abb5u2EvuYsLJhFZ1RDXhgn9aBlrBNIByx9pwmPw66Y">

Great!  If you test it fully, I think you should release one PR so that every one can enjoy it

**Comment by Jont828** [comment]
@EmmetZ Do you want to open a PR with this? Seems pretty straightforward to me and could toggle it with a setting if people don't want it enabled.

**Comment by Jont828** [comment]
If anyone else is curious, I set this up with claude code. Here's what goes in parser.js. The icons are from GitHub's @primer/octicons, but I added it as hard coded SVG so we don't need to take an npm dependency.

```js
  onWillParseMarkdown: async function (markdown) {
    return new Promise((resolve, reject) => {
      // SVG icons for each alert type (GitHub-style octicons)
      const icons = {
        note: '<svg class="octicon" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM6.5 7.75A.75.75 0 0 1 7.25 7h1a.75.75 0 0 1 .75.75v2.75h.25a.75.75 0 0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h.25v-2h-.25a.75.75 0 0 1-.75-.75ZM8 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>',
        tip: '<svg class="octicon" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M8 1.5c-2.363 0-4 1.69-4 3.75 0 .984.424 1.625.984 2.304l.214.253c.223.264.47.556.673.848.284.411.537.896.621 1.49a.75.75 0 0 1-1.484.211c-.04-.282-.163-.547-.37-.847a8.456 8.456 0 0 0-.542-.68c-.084-.1-.173-.205-.268-.32C3.201 7.75 2.5 6.766 2.5 5.25 2.5 2.31 4.863 0 8 0s5.5 2.31 5.5 5.25c0 1.516-.701 2.5-1.328 3.259-.095.115-.184.22-.268.319-.207.245-.383.453-.541.681-.208.3-.33.565-.37.847a.751.751 0 0 1-1.485-.212c.084-.593.337-1.078.621-1.489.203-.292.45-.584.673-.848.075-.088.147-.173.213-.253.561-.679.985-1.32.985-2.304 0-2.06-1.637-3.75-4-3.75ZM5.75 12h4.5a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1 0-1.5ZM6 15.25a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5h-2.5a.75.75 0 0 1-.75-.75Z"></path></svg>',
        important: '<svg class="octicon" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M0 1.75C0 .784.784 0 1.75 0h12.5C15.216 0 16 .784 16 1.75v9.5A1.75 1.75 0 0 1 14.25 13H8.06l-2.573 2.573A1.458 1.458 0 0 1 3 14.543V13H1.75A1.75 1.75 0 0 1 0 11.25Zm1.75-.25a.25.25 0 0 0-.25.25v9.5c0 .138.112.25.25.25h2a.75.75 0 0 1 .75.75v2.19l2.72-2.72a.749.749 0 0 1 .53-.22h6.5a.25.25 0 0 0 .25-.25v-9.5a.25.25 0 0 0-.25-.25Zm7 2.25v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"></path></svg>',
        warning: '<svg class="octicon" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M6.457 1.047c.659-1.234 2.427-1.234 3.086 0l6.082 11.378A1.75 1.75 0 0 1 14.082 15H1.918a1.75 1.75 0 0 1-1.543-2.575Zm1.763.707a.25.25 0 0 0-.44 0L1.698 13.132a.25.25 0 0 0 .22.368h12.164a.25.25 0 0 0 .22-.368Zm.53 3.996v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"></path></svg>',
        caution: '<svg class="octicon" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M4.47.22A.749.749 0 0 1 5 0h6c.199 0 .389.079.53.22l4.25 4.25c.141.14.22.331.22.53v6a.749.749 0 0 1-.22.53l-4.25 4.25A.749.749 0 0 1 11 16H5a.749.749 0 0 1-.53-.22L.22 11.53A.749.749 0 0 1 0 11V5c0-.199.079-.389.22-.53Zm.84 1.28L1.5 5.31v5.38l3.81 3.81h5.38l3.81-3.81V5.31L10.69 1.5ZM8 4a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5A.75.75 0 0 1 8 4Zm0 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>'
      };

      // Title case names
      const titles = {
        note: 'Note',
        tip: 'Tip',
        important: 'Important',
        warning: 'Warning',
        caution: 'Caution'
      };

      const calloutRegex = /^> ?\[!(?<type>\w+)\](?<title>.*)?\r?\n(?<content>(?:>.*\r?\n?)*)/gm;
      
      const newMarkdown = markdown.replace(
        calloutRegex,
        (match, type, title, content) => {
          const alertType = type.toLowerCase();
          const icon = icons[alertType] || icons.note;
          const displayTitle = title && title.trim() ? title.trim() : titles[alertType] || type;

          const alertContent = content
            .replace(/^> ?/gm, "")
            .trim();

          return `<div class="markdown-alert markdown-alert-${alertType}">
<p class="markdown-alert-title">${icon} ${displayTitle}</p>

${alertContent}

</div>

`;
        }
      );
      return resolve(newMarkdown);
    });
  },
```

Then, create a CSS file with the following in `.local/state/crossnote/style.less`.

```css
/* Please visit the URL below for more information: */
/*   https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css */

.markdown-preview.markdown-preview {
  // modify your style here

  /* GitHub-style markdown alerts/callouts */
  /* Colors from github-markdown-css / @primer/primitives */
  
  /* Default to light mode colors */
  --color-note-fg: #0969da;
  --color-note-border: #0969da;
  --color-tip-fg: #1a7f37;
  --color-tip-border: #1a7f37;
  --color-important-fg: #8250df;
  --color-important-border: #8250df;
  --color-warning-fg: #9a6700;
  --color-warning-border: #9a6700;
  --color-caution-fg: #d1242f;
  --color-caution-border: #cf222e;

  .markdown-alert {
    padding: 8px 16px;
    margin-bottom: 16px;
    color: inherit;
    border-left: 0.25em solid var(--color-note-border);

    > :first-child {
      margin-top: 0;
    }

    > :last-child {
      margin-bottom: 0;
    }

    .markdown-alert-title {
      display: flex;
      font-weight: 500;
      align-items: center;
      line-height: 1;
      margin-bottom: 4px;

      .octicon, svg {
        margin-right: 8px;
        fill: currentColor;
        display: inline-block;
        overflow: visible;
        vertical-align: text-bottom;
      }
    }

    p {
      margin-top: 0;
      margin-bottom: 10px;

      &:last-child {
        margin-bottom: 0;
      }
    }

    /* Note - Blue */
    &.markdown-alert-note {
      border-left-color: var(--color-note-border);

      .markdown-alert-title {
        color: var(--color-note-fg);
      }
    }

    /* Tip - Green */
    &.markdown-alert-tip {
      border-left-color: var(--color-tip-border);

      .markdown-alert-title {
        color: var(--color-tip-fg);
      }
    }

    /* Important - Purple */
    &.markdown-alert-important {
      border-left-color: var(--color-important-border);

      .markdown-alert-title {
        color: var(--color-important-fg);
      }
    }

    /* Warning - Yellow/Orange */
    &.markdown-alert-warning {
      border-left-color: var(--color-warning-border);

      .markdown-alert-title {
        color: var(--color-warning-fg);
      }
    }

    /* Caution - Red */
    &.markdown-alert-caution {
      border-left-color: var(--color-caution-border);

      .markdown-alert-title {
        color: var(--color-caution-fg);
      }
    }
  }
}

/* Dark theme colors based on previewColorScheme setting */
/* MPE uses data-color-mode attribute or applies dark theme classes */
html[data-color-mode="dark"] .markdown-preview.markdown-preview,
html.dark .markdown-preview.markdown-preview,
body[data-color-mode="dark"] .markdown-preview.markdown-preview,
body.dark .markdown-preview.markdown-preview,
.markdown-preview.markdown-preview[data-color-mode="dark"],
.markdown-preview.markdown-preview.dark {
  --color-note-fg: #4493f8;
  --color-note-border: #1f6feb;
  --color-tip-fg: #3fb950;
  --color-tip-border: #238636;
  --color-important-fg: #ab7df8;
  --color-important-border: #8957e5;
  --color-warning-fg: #d29922;
  --color-warning-border: #9e6a03;
  --color-caution-fg: #f85149;
  --color-caution-border: #da3633;
}

/* Handle previewColorScheme: "auto" - follows system preference */
@media (prefers-color-scheme: dark) {
  html[data-color-mode="auto"] .markdown-preview.markdown-preview,
  body[data-color-mode="auto"] .markdown-preview.markdown-preview,
  .markdown-preview.markdown-preview[data-color-mode="auto"] {
    --color-note-fg: #4493f8;
    --color-note-border: #1f6feb;
    --color-tip-fg: #3fb950;
    --color-tip-border: #238636;
    --color-important-fg: #ab7df8;
    --color-important-border: #8957e5;
    --color-warning-fg: #d29922;
    --color-warning-border: #9e6a03;
    --color-caution-fg: #f85149;
    --color-caution-border: #da3633;
  }
}
```
