### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TTycho** [shd101wyy/vscode-markdown-preview-enhanced#1970]
**Describe the bug**
I am trying to export a markdown presentation to HTML but I am missing the option S to show speaker notes.

**Environment**
- OS: Linux
- VSCode: 1.87.1
- Markdown Preview Enhanced: 0.8.13
- Electron: 27.3.2
- Chromium: 118.0.5993.159
- Node.js: 18.17.1

**To Reproduce**

When exporting a markdown presentation MPE creates a directory `revealjs_deps`. Here are only notes.js and notes.html, they seem to be copied from the `crossnote` directory 'notes' but lack `plugin.js` and `speaker-view.html`.

The notes.js is a different one then when MPE was using mume. When I copy the mume version to `revealjs_deps`, the 'S' option appears again in the help ('?') and the speakerview works again.

I can't locate the origin of the file in the mume notes directory. The notes.js file from Revealjs 4.0.0 seems the same as 4.6.0, so I dont know where this 4.4kb notes.js file came from.

**Expected behavior**
A speaker view (option S in the help)

**Markdown file**
I am using the following front matter options:

```
---
presentation:
  showNotes: false
  width: 960
  height: 700
  controls: true
  center: true
  previewLinks: true
  maxScale: 5
  enableSpeakerNotes: true
---

```

**Related**
When exporting the presentation as HTML, either as 'offline' or 'cdn hosted', a bit of css (version 4.5.0) is pasted in the resulting HTML while the reveal javascript (version 4.6.0) is fetched with `<link>` tags. This css is also available locally and in the package on jsdeliver.net, but that aside.
