### ISSUE TITLE
[BUG] Cannot transform to pdf successfully.

### ISSUE THREAD

**Issue by EkSulfur** [shd101wyy/vscode-markdown-preview-enhanced#2025]
**Describe the bug**
I tried to export pdf though Puppeteer after I set the correct Chorme path. But there is no reaction.

**Environment**
- OS: Windows 11
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**
1. set chorme path
2. right click the preview page
3. select Export
4. select Chorme(Puppeteer)
5. select PDF

**Expected behavior**
PDF exported successfully

**Comment by engelhro** [comment]
I have the same problem – I don't know since when it exists, but I recently upgraded two Chrome installations to v127.0.6533.x, and with both I see the same behaviour (VSCode v1.91.1, Markdown Preview Enhanced v0.8.13).

I see in the task explorer that several Chrome instances have been started, but they seem to "hang" and don't finish the MD → PDF conversion, thus producing no output 😢.

**Comment by Bavarian-Barbarian** [comment]
Same here.

VS shows the follwoing error:

>RG: Protocol error (Page.printToPDF): Invalid parameters Failed to deserialize params.pageRanges - BINDINGS: string value expected at position 833

**Comment by Bavarian-Barbarian** [comment]
Hi @engelhro,

I found out, that I had pageRanges with no value defined in the yaml settings 

```
puppeteer:
    format: "A4"
    landscape: false
    timeout: 3000 # <= Special config, which means waitFor 3000 ms
    pageRanges: # e.g. 1-5 <-- this line caused the error
    printBackground: false #true
    margin:
      top: '15mm'
      bottom: '15mm'
      left: '20mm' 
      right: '20mm'
```

according to [https://github.com/puppeteer/puppeteer/blob/v1.9.0/docs/api.md#pagepdfoptions](https://github.com/puppeteer/puppeteer/blob/v1.9.0/docs/api.md#pagepdfoptions):
> pageRanges <[string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)> Paper ranges to print, e.g., '1-5, 8, 11-13'. Defaults to the empty string, which means print all pages.

emtpy strings would be allowed.

I did not change the settings recently but pdf export did stop working. Maybe Markdown Preview Enhanced does not like "empty strings" anymore. 

Maybe you have the same issue?
