### ISSUE TITLE
[BUG] `toc: true` Not working on MacOS

### ISSUE THREAD

**Issue by pengyuwei** [shd101wyy/vscode-markdown-preview-enhanced#2084]
**Describe the bug**
The same document can work normally as described in the document on Windows, with a directory tree appearing on the left side. However, on MacOS, no matter how configured, the directory tree cannot appear.

**Environment**
- OS: MacOS 10.15.7, Windows11Pro 23H2 22631.4602
- VSCode: 1.95.3 (Universal，MacOS),  1.96.0（Windows）
- Markdown Preview Enhanced: v0.8.15

**To Reproduce**
1. Preview Markdown
2. Ctrl+S or File Menu/Save
3. Open the automatically generated HTML page using a browser

**Expected behavior**
The directory tree appears on the left, or the expand button of the directory tree appears

**Markdown file**
```
html:
  embed_local_images: false
  embed_svg: true
  offline: true
  toc: true
export_on_save:
  html: true
toc:
  depth_from: 1
  depth_to: 4
  ordered: false

# Tile
...
```
toc: true 
or 
According to the documentation, not writing TOC will generate hidden TOC, which can be expanded by clicking the button to expand the left directory tree

**Screenshots**
None

**Additional context**
It's not a syntax or usage issue, as the same document can appear in the left directory tree normally under Windows
