### ISSUE TITLE
[BUG] 一行文本过多时，导出pdf时，该行文字无法自动换行，导致被截断，显示不完整，

### ISSUE THREAD

**Issue by shawnnnnnnnnnnn** [shd101wyy/vscode-markdown-preview-enhanced#2099]
如题所示

VSCODE 中MD 及预览

![Image](https://github.com/user-attachments/assets/b005587a-af31-43cd-a2c3-f94b1a6c449c)

导出效果

![Image](https://github.com/user-attachments/assets/79099e4e-7cff-43b5-bbaf-38ae32adc18c)

**Comment by ffaffAHA** [comment]
`Ctrl + Shift + P` Set  `EMP Costomize CSS (workspace)`  or  `EMP Costomize CSS(Global)  ` `style.less` write in this code
```less
body {
  /* 隐藏水平滚动条，防止页面内容溢出时出现水平滚动 */
  overflow-x: hidden;
  /* 设置文字两端对齐，使段落看起来更加整齐 */
  text-align: justify;
  /* 允许单词在任意位置换行，防止单词过长溢出容器 */
  word-break: break-all;
  /* 注释掉的最大宽度设置，原计划为 A4 纸的宽度（21cm） */
  /* max-width: 21cm; //A4纸宽度 */
  /* 去除 body 元素的外边距 */
  margin: 0;
  /* 去除 body 元素的内边距 */
  padding: 0;
}
```
