### ISSUE TITLE
[BUG] backround-image property cant use in body element (local and relative path svg)

### ISSUE THREAD

**Issue by Rail27** [shd101wyy/vscode-markdown-preview-enhanced#2133]
**Describe the bug**
When using background-image property as "local" and "relative path" svg, its not do anything

**Environment**
- OS: Linux (Arch Linux: Latest 2025/05/27)
- VSCode: 1.100.2 (Proprietary)
- Markdown Preview Enhanced: 0.8.18

**To Reproduce**
1. Create style of Markdown Preview Enhanced
2. Change style to folowing:
```less
body {
	background-image: url('./Image.svg');
}
.markdown-preview.markdown-preview {
	background-image: url('./Image.svg');
}
```

**Expected behavior**
When set the "background-image" as local and relative path, it'll show background images in target element

**Markdown file**
```
# Test
test
```

**Screenshots**
![Screenshot Image](https://github.com/user-attachments/assets/f4b6ec34-48a5-4a36-9bc4-c68b8a348f59)

**Additional context**
But I can use in "real url".
Style.less:
```less
body {
	background-image: url('https://duckduckgo.com/favicon.ico');
}
```
Screenshot:
![DuckDuckHell](https://github.com/user-attachments/assets/9f782bc7-a9bd-4296-8be2-4f965c66abad)
