### ISSUE TITLE
vscode自动升级后style.less和mermaid的设定被初始化

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/vscode-markdown-preview-enhanced#22]
如题，今天自动升级到1.14后发现设定被初始化了

**Comment by coolboy0961** [comment]
另外style.less的设定不管用了

```

html body {
  // modify your style here
  // eg: background-color: blue;

  .markdown-preview-enhanced.markdown-preview-enhanced {
    // modify your style here
    // eg: background-color: blue;
    //テーブルをもっとコンパクトにする
    svg{
      max-width: none;
    }
    th, td {
      padding: 5px 10px;
    }
    //タイトル行の背景をグレーにする
    th {
      background: #EEE;
    }
    //テーブルの全内容を1ページに収めるようにする
    table{
      width:100%;
      table-layout: fixed;
      word-break: break-word;
    }
    width: 100%;
    // custom pdf output style

    .mermaid .today {
      stroke: red ;
      stroke-width: 0px ;
    }
    //章節番号設定開始
    h1 {
        counter-reset: h2counter;
    }
    h2 {
        counter-increment: h2counter;
        counter-reset: h3counter;
    }
    h3 {
        counter-increment: h3counter;
        counter-reset: h4counter;
    }
    h4 {
        counter-increment: h4counter;
    }
    h2:before {
        content: counter(h2counter) ". ";
    }
    h3:before {
        content: counter(h2counter) "." counter(h3counter) ". ";
    }
    h4:before {
        content: counter(h2counter) "." counter(h3counter) "." counter(h4counter) ". ";
    }
    //章節番号設定終了
  }

}    
```

**Comment by shd101wyy** [comment]
把 `.markdown-preview-enhanced.markdown-preview` 给删掉吧。 

```less

html body {
  // modify your style here
  // eg: background-color: blue;

    // modify your style here
    // eg: background-color: blue;
    //テーブルをもっとコンパクトにする
    svg{
      max-width: none;
    }
    th, td {
      padding: 5px 10px;
    }
    //タイトル行の背景をグレーにする
    th {
      background: #EEE;
    }
    //テーブルの全内容を1ページに収めるようにする
    table{
      width:100%;
      table-layout: fixed;
      word-break: break-word;
    }
    width: 100%;
    // custom pdf output style

    .mermaid .today {
      stroke: red ;
      stroke-width: 0px ;
    }
    //章節番号設定開始
    h1 {
        counter-reset: h2counter;
    }
    h2 {
        counter-increment: h2counter;
        counter-reset: h3counter;
    }
    h3 {
        counter-increment: h3counter;
        counter-reset: h4counter;
    }
    h4 {
        counter-increment: h4counter;
    }
    h2:before {
        content: counter(h2counter) ". ";
    }
    h3:before {
        content: counter(h2counter) "." counter(h3counter) ". ";
    }
    h4:before {
        content: counter(h2counter) "." counter(h3counter) "." counter(h4counter) ". ";
    }
    //章節番号設定終了
}    
```
