### ISSUE TITLE
关于"Save as Markdown"的输出文件名问题

### ISSUE THREAD

**Issue by hjianhao** [shd101wyy/vscode-markdown-preview-enhanced#252]
我的文件时overview-raw.md

输出配置是：
```
---
markdown:
  image_dir: ./images
  path: ./overview.md
  ignore_from_front_matter: true
  absolute_image_path: false
---
```

按理输出的文件应该是overview.md，但是我多执行几次"Save as Markdown"后，输出文件名就变成了overview-raw_.md了
