### ISSUE TITLE
PlantUML image width

### ISSUE THREAD

**Issue by Hipska** [shd101wyy/vscode-markdown-preview-enhanced#266]
Hi, I have a similar problem as in #19 it seems, but as I don't speak Japanese, I can't figure out what could be the solution.

I don't want my images to have a limited width, so I tried this in my custom CSS:

```less
.markdown-preview.markdown-preview {
  // modify your style here
  // eg: background-color: blue;  
  svg {
    max-width: none;
    background-color: blue;
  }
}
```

Background color only there to see if the css works.
I also tried `width: 150;` to see any changes, but nothing seems to work.

Could there also be an option to change the plantUML output to be an image instead of sag?

**Comment by shd101wyy** [comment]
How about adding `!important` after `none`?
Can I see your plantuml code so I can test it.
Thanks

**Comment by Hipska** [comment]
Strange, it works with a [basic](https://www.planttext.com/?text=oyjFILKeIIqkCU3AWp4D4KmZ1DCOmJH1C4qHJ3C4qnp1j40mBRcum3Ofw1PbfcUKwDf1RGDRX2fe31OqGHKq1GkQeGgQWmKjK0Kj0G00) plantUML code even without the `!important`.

[This advanced](https://www.planttext.com/?text=fLTTZw8m57tdLpG-pJvWeEw7cic-p6uocyaOat7tORC9gQKgWMb9GNUpc_dlMw1WeIs2Og92xpczz_JqMd72ZY6Oh4Z-c_4OXEGKOP9D0ChgxmwkGfxGBaO09ySi9xmCY8id3i8vus3obORWcCaHGiEWk74SJd2Ew3uXOF9CSXvXW5cIY8SHesUoVmuG5sMX25iLxtxzhBWmUqqP9JG7avmaPC_HhfpbjIGC927ZGJqQ-2NshSiARsE5alNDL5OcGj6UzDGqiyoE4Tyowk8aml612TdKD0fQ4bGXigmklC6vGl6JN84sl0anKuZgqaEKazuSwY0pnL_6Oa9Iq-pDa88CKOwsA1FIIDrqMBWLyGt0A0TmtS_sIi4IF1ItZyNjBxfvM2_dFfnPA5NWlSPR9ZC8Q1DjL3QAP3fdfyQVZ3sLiHKfzESMzx-_sN_mTlyPASRvpqWno7zmfFzWl_zWh__WjVw3Pl_1OK2RQ5Vwpy3PgT7kl_8Zeg8RxX0MKl_ujWP_fkNBq6d53q9mYjA1e9IJJ2myQc2EKaIRqR1ATVzOWiVDPYqJzxnFLv10dSJHz5JQW29djuOMqy9RU3r4S1oHpjJkMzDf3vVLDpr674zuAKMNH_j3Vc73gMLx2vsotLYDZAhtpUuMpbRQweUwhMej5QMHrR9DH1TQd3GGHLQW73VFc174yS6AhOPRIfkJiffBpjvIUkx97N-9CY4xHMrJPa9PUUfKCp0Ty4G6BwjdaS7tB-kb_z4VY8CQpkcRHDdqdNQWRVg-EKVGEEMXMjq_bkhButXZTJW81mqunxPDRHOuhwZMPQnKbcvmTfEv8_HXYlJglnaoaxkNTnLwvddcPDe6xy0LD_y7) code does still keep a fixed width?

**Comment by jraygauthier** [comment]
Try this:

```css
.markdown-preview.markdown-preview p > svg[data-diagram-type] {
  width: 100% !important;
  height: auto !important;
  display: block;
}
```

works fine here in order to make the diagram fit the preview pane width (just like those mermaid diagrams).

I think this should be included as part of the extension's default `*.css`.
