### ISSUE TITLE
The color of sidebar-toc and slidebar-toc_btn does not change in HTML export.

### ISSUE THREAD

**Issue by Bocha91** [shd101wyy/vscode-markdown-preview-enhanced#280]
Hello

I'm making a dark theme and want to export a dark HTML theme.

style.less

``` css
.markdown-preview {
    color: #bdcadb;
    background: #1c1f2b;
    strong {
        color: #f8f8f8;
    }
    h1, h2, h3, h4, h5, h6 {
        color: #bdcaeC;
    }
    hr { 
        background-color: #2d3143;
    }
    code, pre {
        background-color: #2d3143;// #000000;
        color: #70ff00;
    }
    pre {
        font-size: 1.2em !important;
    }
    a {
        color: #3eb1d0;
        #slidebar-toc_btn {
            color: #e2e2e2;
        }
    }
}
.md-sidebar-toc.md-sidebar-toc {
    background-color: #1c1f2b;
    color: #e2e2e2;
}
#slidebar-toc_btn {
  color: #e2e2e2;
}
```
The color of sidebar-toc and slidebar-toc_btn does not change in HTML export.
Am I doing wrong for exporting to HTML?

**Comment by Bocha91** [comment]
I came up with a workaround on how to change the color of sidebar-toc and slidebar-toc_btn. Fix color with an embedded script

Add another script file to the beginning of the .md file

```
@import "my-style.less"
@import "md_plugin.js"

```
md_plugin.js
``` javascript
function OnLoadReady(fn) {
  if (document.readyState != 'loading'){ fn(); //console.log("loading")
  }else {   document.addEventListener('DOMContentLoaded', fn); }
};

OnLoadReady(function(){
  document.querySelector('.md-sidebar-toc').style.backgroundColor = "var(--main-background)";
  document.querySelector('#sidebar-toc-btn').style.color = "var(--btn_color)"; 
});
```
my-style.less
``` less
:root {
    --main-background:  #1c1f2b; 
    --main-text-color:  #bdcadb; 

    --h-color:          #bdcaeC;    
    --strong-color:     #f8f8f8; 
    --a-color:          #3eb1d0;    

    --hr-background:    #2d3143;

    --pre-background:   #0000004a;  
    --pre-color:        #70ff00;
    --btn_color:        #3eb1d0;
    --btn_color-hover:  #e2e2e2;
}
  
.markdown-preview {
    background-color: var(--main-background);
    color: var(--main-text-color);
    h1, h2, h3, h4, h5, h6 {
        color: var(--h-color);
        text-align: center;
    }
    strong {
        color: var(--strong-color);
    }
    hr { 
        background-color: var(--hr-background);
    }
    code, pre {
        background-color: var(--pre-background);
        color: var(--pre-color);
    }
    pre {
        font-size: 1.0em !important;
    }
    a {
        color: var(--a-color);
    }
    th {
        color: var(--h-color);
    }
    summary {
        color: yellow;
        background-color: darkslateblue;
        padding: 5px;
        font-style: italic;
        border-radius: 4px;
        margin: 2px;
    }
}

.md-sidebar-toc {
    
    background-color: var(--main-background);
    color: var(--a-color);
    code, pre {
        background-color: var(--pre-background);
        color: var(--pre-color);
    }
    a {
        color: var(--a-color);
    }

}

#sidebar-toc-btn {
    color: var(--btn_color);
    a:hover {
        color: var(--btn-color-hover);
    }
}
```

It is also necessary to adjust color themes for languages for a dark theme, can someone tell me where to get the finished ones?
