### ISSUE TITLE
TOC sidebar not displayed

### ISSUE THREAD

**Issue by mcbsd** [shd101wyy/vscode-markdown-preview-enhanced#342]
Hi,

could somebody of you or even the author help me to find out why TOC sidebar is not displayed?
It should be even enabled by default.

This is what I have at the beginning of .md file:
```
---
html:
  embed_local_images: true
  embed_svg: true
  offline: true
  toc: true
---
```
If I change embed_local_images to false, the change is reflected at the export which means that configuration is taken from this front matter.
Whatever I set for toc (true, false, undefined) it has no effect on the export.
I now use [TOC] in the .md file content to generate content, but I would like to have it as sidebar.

plugin version: 0.5.3
OS: Windows 10
VSC: 1.44.2

Thanks for any help
