### ISSUE TITLE
使用 Pandoc 导出 PDF 时中文不显示

### ISSUE THREAD

**Issue by weidongzhou1994** [shd101wyy/vscode-markdown-preview-enhanced#360]
如题：
![image](https://user-images.githubusercontent.com/40510496/82682888-90f6db00-9c82-11ea-98ac-679a38e0b58f.png)
![image](https://user-images.githubusercontent.com/40510496/82682959-aff56d00-9c82-11ea-8611-716e400fad42.png)

**Comment by shd101wyy** [comment]
我猜测是你的 Texlive 没安装中文？如果用 ubuntu 的话可以 `sudo apt install -y texlive-lang-chinese`

**Comment by weidongzhou1994** [comment]
并不是，是不是需要指定中文字体？？

**Comment by weidongzhou1994** [comment]
我直接在命令行用pandoc导出的pdf 文档指定中文字体后就可以显示了

**Comment by shd101wyy** [comment]
hmmmm 我研究下，理论上来讲我也是运行了 pandoc 命令而已

**Comment by fedlin** [comment]
首先，要使用xelatex作为pdf-egine,其次要指定中文字体，可以在md文件头部加入front-matter来声明要传递的参数：
```
---
title: "test"
author: aaaa
date: 01,01,2021
output:
  pdf_document:
     latex_engine: xelatex
     toc: true
documentclass: ctexart
mainfont: 微软雅黑
---
```
或者把以上内容放在一个放在与要输出的md文件同一目录下的 _output.yaml文件内即可，放入yaml文件不需要上下的横线，就可以用MPE pandoc输出中文的pdf了，更多的调整选项可参见pandoc手册的Variables部分 其中 Metadata variables 和 Variables for LaTeX
