### ISSUE TITLE
The import file converted with the Save as Markdown command has a'{}' at the end of the link.

### ISSUE THREAD

**Issue by tama46** [shd101wyy/vscode-markdown-preview-enhanced#372]
My code specifies the plantuml file with `@import` as shown below.

```
---
markdown:
  image_dir: /images
  path: /sample.md
  ignore_from_front_matter: true
  absolute_image_path: true
export_on_save:
  markdown: true
---

@import "sample.puml"
```

When this is output to md file with Save as Markdown, extra parentheses'{}' are added at the end of the link of the file that converted plantuml into an image.

`![](/images/ab15336182ea12c5073d7fe19765fd250.png?0.9918091048517237){}  `

If you display it as it is, extra parentheses will be displayed below the image.
There was no problem until about a month ago.
Events like this have recently become more common.
