### ISSUE TITLE
希望导出的html文档中显示的代码块可以自动换行

### ISSUE THREAD

**Issue by wu-kan** [shd101wyy/vscode-markdown-preview-enhanced#385]
使用 html 导出文档然后打印成 pdf 的时候发现过长的代码行会有一个难看的滚动条，超出的代码也会溢出，不是很美观，希望能在打印的时候去掉，如下。

![image](https://user-images.githubusercontent.com/44857941/86512393-9d9b5100-be34-11ea-8552-b71ebadc50a6.png)

在页面的默认 css 里面加上下述内容应该就可以了…

```css
@media print{
    code[class*="language-"], pre[class*="language-"] {
        white-space: pre-wrap;
    }
}
```
