### ISSUE TITLE
[Feature Request] Specify theme of exported PDF, independent from PrintBackground

### ISSUE THREAD

**Issue by ZZYSonny** [shd101wyy/vscode-markdown-preview-enhanced#446]
I am previewing the markdown document in one-dark theme. But I would like to export as PDF in light theme with background (so code get surrounded in colored boxe). 

Currently `markdown-preview-enhanced.printBackground` option also sets print theme to current preview theme. So if I want the colored boxes, I get a dark document. (unless I manually change my preview theme)

It will be much more useful to add an option `markdown-preview-enhanced.pdfPrintTheme`.

**Comment by zhengxiaoyao0716** [comment]
Same problem, and I think this problem comes from the wrong design of the upstream repository ([crossnote](https://github.com/shd101wyy/crossnote/blob/fd6ac5421298ca6e09a0520ac566fe4611a13ac0/src/markdown-engine/index.ts#L1395C45-L1395C60)).

It can be solved temporarily by adding front-matter to the `.md` file header to overwrite it:

``` yaml
---
puppeteer:
  # it seems a bug since the comments says "You can also set `print_background`
  # in front-matter for individual files.", instead of `printBackground`.
  # print_background: true
  printBackground: true
---
```
