### ISSUE TITLE
Reference to other notes are not working anymore when rendering

### ISSUE THREAD

**Issue by alexis-renard** [shd101wyy/vscode-markdown-preview-enhanced#556]
## The issue context
While rendering the preview one _normal_ markdown is still working fine, neither the note references (include a note into another) or the automatic use of the referenced notes titles are working anymore. Todo lists are still working fine as well.

## Technical info
* OS : Ubuntu 20.04
* Text editor used : VS Codium 1.63.2
* Dendron version used : 0.73.1
* Plugin version used : 0.10.47
* Usage : multi vault workspace 

## What I tried to do
* I tried to uninstall/reinstall dendron and all associated plugins (including this one).
* I had the original markdown-preview-enhanced activated before, uninstalled it completely to check if it would work better. 
* I have not tried with vscode (not codium) but I would prefer to stick to it if possible

## More info about the issue
Don't know exactly when it started to appear (let's say a few months back) but it has been annoying enough and not fixed by new updates for me to post it here. Might be on my side (I would prefer that actually), I'm searching for a fix here. 
Here a snapshot of the issue : 

![image](https://user-images.githubusercontent.com/16952679/146946975-6e8ac920-4e88-4abe-bff6-6c9a7b073f5b.png)

Using the default Dendron Preview, I have: 

![image](https://user-images.githubusercontent.com/16952679/146947357-d7aaa939-d0d3-4d48-a72e-ed87ad642814.png)

(but it doesn't support my current theme (Atom One Dark) nor the other features brought by the markdown-preview-enhanced plugin)

### Dendron.yml

```yaml
version: 4
useFMTitle: true
useNoteTitleForLink: true
mermaid: true
useKatex: true
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    usePrettyRefs: true
    title: Dendron
    description: Personal knowledge space
    duplicateNoteBehavior:
        action: useVault
        payload:
            ...
    siteLastModified: true
    gh_edit_branch: main
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: false
            leaveTrace: false
            bubbleUpCreateNew: true
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
    randomNote: {}
workspace:
    dendronVersion: 0.71.3
    vaults:
        -
            fsPath: first_one
            ...
        -
            fsPath: second_one
            ...
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
    task:
        name: ''
        dateFormat: ''
        addBehavior: childOfCurrent
        statusSymbols:
            '': ' '
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: 'y'
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
    enableUserTags: true
    enableHashTags: true
preview:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
```

## Conclusion 

Hopeless, I'm posting that issue. Any hints ?
