### ISSUE TITLE
How to make scrollbars wider in preview panel?

### ISSUE THREAD

**Issue by cmcjh** [shd101wyy/vscode-markdown-preview-enhanced#661]
I've found methods to make the editor's scrollbars wider, but the scrollbar of MPE's preview panel didn't change. Is there a way to make the scrollbar of MPE's preview panel wider? (so that I can click and drag it easily)

**Comment by shd101wyy** [comment]
@cmcjh You can run customize css command then add the following style:

```less
.markdown-preview.markdown-preview {
  &::-webkit-scrollbar {
    width: 20px;
  }
}
```
