### ISSUE TITLE
Custom Css has some bugs in HTML(offline) 

### ISSUE THREAD

**Issue by HolmesZhao** [shd101wyy/vscode-markdown-preview-enhanced#680]
Version: 
v0.6.7

Bug:
use HTML(offline):
![image](https://user-images.githubusercontent.com/19728934/221735419-bff1f42b-5e56-4cbb-a108-1871b7d508ea.png)

Normal:
use OpenInBrowser:
![image](https://user-images.githubusercontent.com/19728934/221735456-13d19d94-5b49-4d77-a8e7-64572d262acb.png)

this is my style.less:

```css

@var1: #595959;
@var2: #ebf4ff;
@var3: #7f9cf5;
@var4: #667eea;
@var5: #5a67d8;
@var6: #999999;
@var7: #f8f8f2;
@var8: #272822;
@var9: #8292a2;
@var10: #f92672;
@var11: #ae81ff;
@var12: #a6e22e;
@var13: #e6db74;
@var14: #66d9ef;
@var15: #fd971f;

* {
	box-sizing: border-box;
}
body {
	min-width: 200px;
	max-width: 2760px;
	margin: 0 auto;
	padding: 1em;
	font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
	color: @var1;
	font-size: 16px;
	line-height: 1.8em;
	background-image: linear-gradient(90deg, rgba(60, 10, 30, 0.05) 3%, transparent 0), linear-gradient(1turn, rgba(60, 10, 30, 0.05) 3%, transparent 0);
	background-size: 20px 20px;
	background-position: 50%;
	word-break: break-all;
  background-color: white;
}
blockquote {
	margin-left: 0;
	background-color: @var2;
	border-color: @var3;
	padding-top: 0.5rem;
	padding-bottom: 0.5rem;
	color: @var4;
	> :last-child {
		margin-bottom: 0;
	}
	> :first-child {
		margin-top: 0;
	}
}
strong {
	color: @var5;
	&::before {
		content: '';
	}
	&::after {
		content: '';
	}
}
code, a {
	color: @var5;
}
a {
	border-color: @var4;
}
code {
	background-color: @var2;
}
blockquote, details, dl, ol, p, pre, table, ul {
	margin-bottom: 1rem;
}
ol {
	list-style: decimal;
}
ul {
	list-style: disc;
}
ol, ul {
	padding-left: 2em;
}
h1, h2 {
	border-color: @var5;
	border-style: solid;
	border-top-width: 0px;
	border-right-width: 0px;
	font-weight: 500;
	padding-top: 0.25rem;
	padding-bottom: 0.25rem;
	padding-left: 0.75rem;
}
h1, h2 {
	border-bottom: 1px solid #eaecef ;
	border-left-width: 6px;
}
h1, h2, h3, h4, h5, h6 {
	margin-bottom: 16px;
	line-height: 1.25;
}
blockquote {
	padding-top: 0.5rem;
	padding-bottom: 0.5rem;
	padding-left: 1rem;
	padding-right: 1rem;
	border-left: .25em solid;
}
strong {
	font-weight: bold;
}
code, a {
	font-weight: 500;
}
code, a {
	font-size: unset;
}
a {
	text-decoration: none;
	border-bottom: 1px solid;
}
.footnote-ref {
	border-width: 0px;
}
code {
	font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}
pre > code {
	font-weight: 400;
	color: unset;
	line-height: 1.6;
}
picture img {
	border-radius: 6px;
	display: block;
	margin: 10px auto;
	-o-object-fit: contain;
	object-fit: contain;
	box-shadow: 2px 4px 7px @var6;
}
img {
	max-width: 100%;
	display: block;
	margin: 10px auto;
	object-fit: contain;
	border-radius: 6px;
	box-shadow: 2px 4px 7px @var6;
}
picture {
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	margin-top: 6px;
	margin-bottom: 6px;
}
pre, pre code[class*="language-"] {
	display: block;
	overflow-x: auto;
	padding: 0;
}
pre code[class*="language-"] {
	padding: 12px;
	padding-top: 6px;
}
pre::before {
	content: '';
	display: block;
	background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1NCIgaGVpZ2h0PSIxNCIgdmlld0JveD0iMCAwIDU0IDE0Ij4KICA8ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEgMSkiPgogICAgPGNpcmNsZSBjeD0iNiIgY3k9IjYiIHI9IjYiIGZpbGw9IiNGRjVGNTYiIHN0cm9rZT0iI0UwNDQzRSIgc3Ryb2tlLXdpZHRoPSIuNSIvPgogICAgPGNpcmNsZSBjeD0iMjYiIGN5PSI2IiByPSI2IiBmaWxsPSIjRkZCRDJFIiBzdHJva2U9IiNERUExMjMiIHN0cm9rZS13aWR0aD0iLjUiLz4KICAgIDxjaXJjbGUgY3g9IjQ2IiBjeT0iNiIgcj0iNiIgZmlsbD0iIzI3QzkzRiIgc3Ryb2tlPSIjMUFBQjI5IiBzdHJva2Utd2lkdGg9Ii41Ii8+CiAgPC9nPgo8L3N2Zz4K");
	height: 30px;
	width: 100%;
	margin-bottom: -7px;
	background-size: 40px;
	background-repeat: no-repeat;
}
.svg-markmap-box {
	min-height: 20rem;
	width: 100%;
}
.footnotes {
	padding-top: 0.5rem;
	padding-bottom: 0.5rem;
}
code[class*="language-"], pre[class*="language-"] {
	color: @var7;
	background: none;
	text-shadow: 0 1px rgba(0, 0, 0, 0.3);
	font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
	font-size: 0.9em;
	text-align: left;
	white-space: pre-wrap;
	word-spacing: normal;
	word-break: normal;
	word-wrap: normal;
	line-height: 1.5;
	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;
	-webkit-hyphens: none;
	-moz-hyphens: none;
	-ms-hyphens: none;
	hyphens: none;
}
pre[class*="language-"] {
	padding: 1em;
	margin: .5em 0;
	overflow: auto;
	border-radius: 6px;
}
:not(pre) > code[class*="language-"], pre[class*="language-"] {
	background: @var8;
}
:not(pre) > code[class*="language-"] {
	padding: .1em;
	border-radius: .3em;
	white-space: normal;
}
.token.comment, .token.prolog, .token.doctype, .token.cdata {
	color: @var9;
}
.token.punctuation {
	color: @var7;
}
.token.namespace {
	opacity: .7;
}
.token.property, .token.tag, .token.constant, .token.symbol, .token.deleted {
	color: @var10;
}
.token.boolean, .token.number {
	color: @var11;
}
.token.selector, .token.attr-name, .token.string, .token.char, .token.builtin, .token.inserted {
	color: @var12;
}
.token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string, .token.variable {
	color: @var7;
}
.token.atrule, .token.attr-value, .token.function, .token.class-name {
	color: @var13;
}
.token.keyword {
	color: @var14;
}
.token.regex, .token.important {
	color: @var15;
}
.token.important, .token.bold {
	font-weight: bold;
}
.token.italic {
	font-style: italic;
}
.token.entity {
	cursor: help;
}
```
