### ISSUE TITLE
请问可以改变代码块中的字体吗？

### ISSUE THREAD

**Issue by ziyang-scut** [shd101wyy/vscode-markdown-preview-enhanced#736]
搜到了之前的一个解决方法，说是在`style.less`中添加：
```css
  html body {
    code[class*="language-"], 
    pre[class*="language-"] {
      font-family: "Cascadia Code";
    }
  }
```
如果不选定是什么语言的话是可以改变的，但是选定了之后，比如将语言设置为` ```verilog `就还是会变成默认的字体，请问有什么解决办法吗？
