### ISSUE TITLE
关于YAML标头

### ISSUE THREAD

**Issue by NightSharp** [shd101wyy/vscode-markdown-preview-enhanced#895]
貌似无法正常解释YAML标头
vscode内置的渲染可以正常解释(不显示)
MPE的则会变得很奇怪

比如下面这段

```yaml
---
title: "LaTeX Guide"
author:
  - The Zettlr Team
date: 2020-06-23
...
```

内置渲染直接跳过
但MPE却如下显示
![屏幕截图 2021-12-02 013945](https://user-images.githubusercontent.com/9748063/144285314-34f9c201-627c-4875-b90f-ce7e9d186813.png)
